### GET request hello
GET localhost:8080/response/hello

### GET request random
GET localhost:8080/response/random

### GET request message
GET localhost:8080/response/message

### GET request complex message
GET localhost:8080/response/test

### GET request list
GET localhost:8080/response/list

### GET request map
GET localhost:8080/response/map

### GET request image
GET localhost:8080/response/image

### GET request ResponseEntitu
GET localhost:8080/response/entity
